# Generated by Django 4.2.5 on 2023-12-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_channel_video_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=4000),
        ),
    ]
