# Generated by Django 4.2.5 on 2023-12-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_alter_channel_description_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='cover',
            field=models.FileField(default=None, upload_to='images/cover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(default=None, upload_to='images/thumbnail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=None, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
