# Generated by Django 4.2.5 on 2023-12-27 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_user_profile_pic_alter_channel_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='by',
            field=models.OneToOneField(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='channel', to=settings.AUTH_USER_MODEL),
        ),
    ]
